### PR TITLE
Feature/better failover

### LINKED ISSUE #361: Moped 2 does not retry queries if authentication fails
In Moped 1.5, if a reply came back from the database that it was unauthorized, Moped would check if it had credentials, re-login, and retry. This does not happen in Moped 2. As such, we're getting sporadic failures which if they would just get retried, it would succeed.

E.g.,

```

Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:  [ 6:00:00.151683430] (15197) [ERROR] Caught error in MyProcess #<0x007f56de865538>: #<Moped::Errors::QueryFailure: The operation: #<Moped::Protocol::Query
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:    @length=101
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:    @request_id=19
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:    @response_to=0
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:    @op_code=2004
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:    @flags=[]
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:    @full_collection_name="staging.my_coll"
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:    @skip=0
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:    @limit=-1
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:    @selector={"$query"=>{"_id"=>BSON::ObjectId('55241aa6776f7278ff000000')}, "$orderby"=>{:_id=>1}}
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:    @fields=nil>
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:  failed with error 13: "not authorized for query on staging.my_coll"
Apr 07 14:00:00 worker-st-iad-cld-03 staging.log:  See https://github.com/mongodb/mongo/blob/master/docs/errors.md
```

Exception thrown from lib/moped/operation/read.rb:50:in `block in execute'

### PR DESCRIPTION
**Pull request by jonhyman**
Changes:

* Significantly bumps up the timeout in `Address#resolve`. IMO this timeout should be removed entirely, as it does not play well with multithreaded code. Also adds retry logic to DNS resolution.
* Separates out the shutdown of a pool from the mutex which handles removing it from `pools`, as a shutdown can take a long time or just fail altogether.
* Add `Retryable` and adds more `with_retry` handling. Taken from @wandenberg's pulls; I then added it to `Cursor#get_more`.
* Add more connection failure error codes, as well as some unfortunate magic string detection for connection failure. I don't know if Mongo 3.0 has improved that situation, but at least in 2.4 and 2.6 you still need to inspect the error message since it doesn't always return with an error code.
* Fixes `Node#flush` to actually catch query errors (see https://github.com/mongoid/moped/pull/369)
* Fixes #361; retries auth and retries a query if the reply is `unauthorized?` (that code completely regressed from 1.5.x; `unauthorized?` wasn't called anywhere)

### CODE REVIEW

**Comment by YorickPeterse** [comment]
Seeing how there's a bunch of old commits in here (as far as I can tell) you might want to run a rebase to remove those from the PR.

**Comment by jonhyman** [comment]
@YorickPeterse I had figured that @durran would inspect the changes and apply the ones himself in a single commit he makes, but I can do whatever makes sense.

**Comment by durran** [comment]
@jonhyman Actually if you could rebase that would be great.

**Comment by jonhyman** [comment]
Works for me. I'll submit another pull later in the day when I'm back at my
desk.

**Comment by durran** [comment]
Thanks!

**Comment by jonhyman** [comment]
@durran moved to #380

**Pull request closed without merging**
