### PR TITLE
2.0.1 fix retries operations

### PR DESCRIPTION
**Pull request by wandenberg**
The pull request #324 does not deal with write operations after a replicaset reconfiguration.
And the tests with replicaset simulator does not represent the real world where the election of a new primary can take some seconds.

I moved some of the code I did on pull request #315 to this one based on tag 2.0.1.
I hope you can check and merge it on master.
The tests are done with a real replicaset using the stepDown command.

Regards,
Wandenberg

### CODE REVIEW

**Comment by rakusai** [comment]
i'm looking forward to this fix to be merged ;)

**Comment by matsimitsu** [comment]
So do I, we've been running this on production for a few months now and it works fine :)

**Comment by klamontagne** [comment]
We use it as well.

**Comment by wandenberg** [comment]
Moved to #351

**Pull request closed without merging**
