### PR TITLE
Connection ip issues

### LINKED ISSUE #336: Shouldn't node down! do a pool shutdown?
We are having some weird connection/threading/pool issues when our app first starts up (Moped 2.0.2, Rails 4.1.8, Puma 2.10.2), where Moped can't seem to initially figure out a primary (we are on Heroku cedar-14 stack and Mongolab mongodb 2.6.5).  And the errors persist on seemingly one thread until restarted.  It seems like Moped is leaving some bad connections around, and in digging through the node.rb code, it looks like down! just tries to checkout a new connection and disconnect it instead of shutting down the whole pool?  Shouldn't down! call the ConnectionPool shutdown with a block to shutdown all connections?

### PR DESCRIPTION
**Pull request by durran**
Attempting to resolve #336 and #333

### CODE REVIEW

**Comment by durran** [comment]
@arthurnn The testing from this issue looks good... https://jira.mongodb.org/browse/CS-15755 I've merged in - are you cool with doing a point release?

**Comment by arthurnn** [comment]
:+1:

**Comment by arthurnn** [comment]
https://rubygems.org/gems/moped/versions/2.0.3 relesed

**Comment by durran** [comment]
Thanks!

**Comment by matsimitsu** [comment]
I've tried to run Moped with this fix in production, but instead of a `Moped::Errors::ConnectionFailure` (Could not connect to a primary node for replica set ) I now get:

One: `Moped::Errors::ConnectionFailure`
and [pool size]: `ConnectionPool::PoolShuttingDownError` errors. 

It happens at random throughout the app and only on one of our servers at the same time.

**Pull request merged**
