### PR TITLE
Reduce allocate string object

### PR DESCRIPTION
**Pull request by huacnlee**

### CODE REVIEW

**Comment by huacnlee** [comment]
@durran Anyone review this?

**Comment by durran** [comment]
I'd actually prefer to make them constants instead of freezing them inline and then just use those... If you can change that I'll pull it in. Thanks!

**Comment by huacnlee** [comment]
@durran I don't know how to name that, etc: `l<5q<l<2`

**Comment by huacnlee** [comment]
I have used allocation test, to found those codes, it will allocation many objects because it will be call over and over again, so I wrote this PR.

**Comment by huacnlee** [comment]
@durran Updated

**Comment by durran** [comment]
Thanks!

**Pull request merged**
